# Generated by Django 5.0.1 on 2024-03-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hour',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phoneNum',
            field=models.IntegerField(null=True),
        ),
    ]
