# Generated by Django 5.0.1 on 2024-03-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_hour_student_age_student_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNum',
            field=models.IntegerField(),
        ),
    ]
